name: Build & Deploy Fraud Detection API

on:
  push:
    branches:
      - main
    paths:
      - "api_service/"
      - "Dockerfile"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
            ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t fraud-detection .
          docker tag fraud-detection:latest \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push image to ECR
        run: |
          docker push \
            ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST_IP }} << 'EOF'
            docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
            docker stop fraud-detection || true
            docker rm fraud-detection || true
            docker run -d \
              --name fraud-detection \
              -p 8000:8000 \
              ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
